### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by wirjo** [delegatecash/delegatecash-button#6]
Getting an error. Installed via `yarn` on Node.js 14.17.6 runtime

```
SyntaxError: Unexpected token 'export'
...
export { DelegateCashButton, setPlatformOptions as a, defineCustomElement, setAssetPath as s };
```

Should a `"type":"module"` be added to `package.json`?

**Comment by ryeshrimp** [comment]
@wirjo Can you give more info on your usage? Are you using vanilla, react, svelte?

**Comment by wirjo** [comment]
React. 

Ended up just using a custom implementation though.

**Comment by ryeshrimp** [comment]
@wirjo When I test a `yarn install`, everything works fine on my end. If you were able to send a reproducible repo, I'd love to take a closer look. 

P.S. I'm glad you were able to get a custom implementation! Thanks for using DC
